#!/usr/bin/env python3
"""Generate real 0.3.0-beta.2 collection bytes using its installed CLI."""
import argparse
from pathlib import Path
import subprocess
import sys
import tempfile
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "examples/documents"))
from search import Chunk, cli, encode_document


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", required=True)
    parser.add_argument("--output", default="tests/support/legacy_v03.rs")
    args = parser.parse_args()
    binary = Path(args.binary).resolve()
    version = subprocess.check_output([str(binary), "--version"], text=True).strip()
    if version != "vecnook 0.3.0-beta.2":
        raise ValueError("use the actual published 0.3.0-beta.2 CLI")
    with tempfile.TemporaryDirectory(prefix="vecnook-legacy-") as temporary:
        root = Path(temporary)
        space = [root, "legacy", 2, "fixture-v03:stable-model", "cosine"]
        cli(binary, "docs-init", *space)
        batch = root / "input.tsv"
        original = encode_document(2**64-1, Chunk("legacy.md", 8, 9, "original legacy 한글\n"), ["rust"])
        removed = encode_document(7, Chunk("removed.md", 1, 1, "temporary"), [])
        batch.write_text(f"put\t{2**64-1}\t1,0\t{original}\nput\t7\t0,1\t{removed}\n", encoding="utf-8")
        cli(binary, "docs-batch", *space, batch)
        cli(binary, "docs-checkpoint", *space)
        updated = encode_document(2**64-1, Chunk("legacy.md", 8, 9, "updated legacy 원문\n\r\n"), ["rust"])
        batch.write_text(f"put\t{2**64-1}\t0,1\t{updated}\ndelete\t7\n", encoding="utf-8")
        cli(binary, "docs-batch", *space, batch)
        lines = ["// Generated by tools/generate_legacy_fixture.py using published vecnook 0.3.0-beta.2.",
                 "// Registry source checksum: b1012f762776ed571ca5b492ecdb568a8652d66946e794c0c9e21a7ded03e2fd.",
                 "// Authored fixture text; snapshot/cache at sequence 1, update/delete WAL at sequence 2."]
        for name in ["snapshot.bin", "wal.bin", "index.bin", "collection.bin"]:
            values = list((root / "legacy" / name).read_bytes())
            constant = name.split(".")[0].upper()
            lines.append(f"pub const {constant}: &[u8] = &[")
            lines.extend("    " + ", ".join(map(str, values[i:i+16])) + "," for i in range(0,len(values),16))
            lines.append("];")
        Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("Generated real 0.3.0-beta.2 snapshot/WAL/cache/collection upgrade fixture")


if __name__ == "__main__":
    main()
