#!/usr/bin/env python3
"""Regenerate the public, prepared-query demo using a local embedding model."""
import hashlib
import json
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "examples/documents"))
from search import Ollama, Chunk, document_input, query_input  # noqa: E402

QUERIES = [
    "How do I recover my records after a process crash?",
    "How can I tune efSearch to improve recall and latency?",
    "How can I restrict search to documents with specific tags?",
]


def main():
    client = Ollama()
    model = "embeddinggemma:latest"
    digest = client.digest(model)
    paths = sorted((ROOT / "examples/documents/sample").glob("*.md"))
    chunks = [Chunk(p.name, 1, len(p.read_bytes().decode().splitlines()),
                    p.read_bytes().decode("utf-8")) for p in paths]
    vectors = client.embed(model, [document_input(model, c) for c in chunks]
                           + [query_input(model, q) for q in QUERIES])
    assert len(vectors) == len(chunks) + len(QUERIES)
    assert len({len(v) for v in vectors}) == 1 and client.digest(model) == digest
    def vector(values):
        # Freeze IEEE-754 f32 values with enough decimal digits for round-trip.
        items = []
        for v in values:
            v = struct.unpack("<f", struct.pack("<f", v))[0]
            s = format(v, ".9g")
            items.append(s if "." in s or "e" in s else s + ".0")
        return "&[" + ",".join(items) + "]"
    def string(s):
        return json.dumps(s, ensure_ascii=False)
    header = ["#![allow(clippy::excessive_precision)] // Original f32 values need round-trip literals.",
              "// Generated by tools/generate_demo.py from the MIT sample documents.",
              "// These are model outputs, not model weights. Prepared queries only.",
              f"pub const MODEL: &str = {string(model + '@sha256:' + digest + ':prepared-demo-v1')};",
              f"pub const DIMENSIONS: usize = {len(vectors[0])};",
              "type DemoDocument = (&'static str, &'static str, u32, &'static [f32]);",
              "pub const DOCUMENTS: &[DemoDocument] = &["]
    for c,v in zip(chunks,vectors):
        header.append(f"({string(c.source)}, {string(c.text)}, {c.end_line}, {vector(v)}),")
    header += ["];", "pub const QUERIES: &[(&str, &[f32])] = &["]
    for q,v in zip(QUERIES,vectors[len(chunks):]):
        header.append(f"({string(q)}, {vector(v)}),")
    header.append("];\n")
    (ROOT / "src/demo_data.rs").write_text("\n".join(header), encoding="utf-8")
    manifest = {"model":model,"model_digest":digest,"dimensions":len(vectors[0]),
                "documents":[{"source":p.name,"sha256":hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths],
                "queries":QUERIES,"prompts":"EmbeddingGemma title/text and search-result query, version 1",
                "coordinates":"Original generated f32 values; round-trip decimal literals",
                "embedding_values_sha256":hashlib.sha256(b''.join(struct.pack('<f',v) for vector in vectors for v in vector)).hexdigest(),
                "output_terms":"https://ai.google.dev/gemma/terms",
                "license":"MIT for authored documents and generator; model weights are not redistributed"}
    (ROOT / "docs/demo-provenance.json").write_text(json.dumps(manifest,indent=2)+"\n")
    print(f"Generated {len(chunks)} document and {len(QUERIES)} query embeddings, {len(vectors[0])} dimensions")


if __name__ == "__main__":
    main()
